### ISSUE TITLE
© ISSUE (Leet really love you guys ahhaha)

### ISSUE THREAD

**Issue by samp-pinch** [BoxOfDevs/CommandShop#1]
http://imgur.com/fEaB6XB
@remotevase all we hate leet,don't worry,we should repor them to INTERPOL (Its global LICENSE, so?)

**Comment by samp-pinch** [comment]
Annd leet use this server for about 5months+

**Comment by samp-pinch** [comment]
http://forum.leet.cc/topic/23377/copyright-issue-remotevase-github-com-boxofbits-commandshop-no-profit-for-plugins/2

**Comment by dragonwocky** [comment]
What is wrong with these people. They could at least tell us instead of just waiting till someone like you reports it and we get all annoyed...

**Comment by samp-pinch** [comment]
At first,we no need report this,there is a /LICENSE at all plugins

**Comment by samp-pinch** [comment]
So first read LICENSE before took plugin!

**Comment by dragonwocky** [comment]
And of course @OneThousand has this excuse:
"Already replied to this countless times, PM me if you have an issue with licensing, we are obiding the license that was provided at the time of installing the software."

**Comment by dragonwocky** [comment]
Now I want PocketMine or MCPE to update so we have to update our plugins and they can't use them for profit anymore.

**Comment by samp-pinch** [comment]
LEET have right only for PocketMine 1.6.2dev [Unleashed],cuz i read /LICENSE/ and they can make profit

**Comment by HimbeersaftLP** [comment]
They don't use our plugin, look at the main file, it hasn't got any code in it except fpr the base... bruh

**Comment by dragonwocky** [comment]
Oh lol, I should have checked :P

**Comment by samp-pinch** [comment]
@HimbersaftLP ahhahaha sorry

**Comment by Leejit** [comment]
Yeah, leet is a piece of shit.... so basically, they stole your plugin and use it to earn money on their crappy service ? 

wow.

**Comment by eqMFqfFd** [comment]
@NemanjaMAX @LordJoshie I do not support any side, but you only act as children. I don't understand why do you create non-repository related issues.

It is clear that **LEET** *stolen* the plugin in a certain way, but why users and followers of TheBoxOfDevs' projects do not act of a more mature way?

> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by dragonwocky** [comment]
@kenygamer we take no responsibility for the actions of others, only for the actions of our own team. I have tried to negotiate with the Leet developers, and it seems at the moment there is nothing that can be done about the stolen plugins.

Also, this was not a non-repository related issue. It was a mistake, @NemanjaMAX thought that Leet had used this plugin (they hadn't). As far as I know, Leet has only used our Functions plugin.

Anyway, this issue was closed for a reason. Please do not continue conversations in closed issues unless there is a need other than just to state your opinion months after.

**Comment by AvgZing** [comment]
Just as an additional clarification, we cannot remove the plugin from leet, but we can stop them from using newer versions and we can stop support for older plugin versions. That is exactly what we have done with Functions

**Comment by lavender-sys** [comment]
Did leet use our plugin or not?

**Comment by HimbeersaftLP** [comment]
@Dog2puppy They used Functions but they didn't use commandshop

**Comment by lavender-sys** [comment]
But then what's the screenshot of?

**Comment by HimbeersaftLP** [comment]
@Dog2puppy It's just a permission selling plugin from leet (or stolen from another dev, who knows xD)

**Comment by lavender-sys** [comment]
XD
