### ISSUE TITLE
RankShopUI

### ISSUE THREAD

**Issue by nivowski** [BoxOfDevs/CommandShop#13]
### Brief description

Hi, I'm asking for if you can do a RankShopUI because it's don't exist i think because i searched a lot.Bes regard
### Steps to reproduce

1. ...
2. ...
3. ...

### Server Information
* CommandShop Version: 
* Software Version: 
* Server OS: 

### CrashDumps/Errors
```
Paste your CrashDump or error by replacing this text (DON'T delete the backticks!)
```

**Comment by HimbeersaftLP** [comment]
Closing in favour of #10
