### ISSUE TITLE
receive the same item several times

### ISSUE THREAD

**Issue by llronaldoll** [BoxOfDevs/CommandShop#14]
When I click on the card to buy an item, I receive the same item several times

**Comment by AvgZing** [comment]
More steps to reproduce would be helpful. What item are you attempting to buy? What does the sign display? What are the commands that you entered in order to set it up so far?

**Comment by llronaldoll** [comment]
I just realized that this happens only in the windows 10 version
this click spam happens with any command but only in the version windows 10

**Comment by AvgZing** [comment]
Well, that makes more sense. Win10 edition spam interactevent many times per tick, which is more than likely the root cause of this issue. 
Feel free to join our discord server at https://discord.me/bod for a faster reply from other developers and team members.

**Comment by HimbeersaftLP** [comment]
We should put a cooldown in place to prevent this from happening

**Comment by HimbeersaftLP** [comment]
Added in 4be927d102d979cd7428cde0865b0b26fc06e79b, use the latest Poggit build to test it.

**Comment by HimbeersaftLP** [comment]
Removed that annoying message ("Blocked 1 Interact spam") that I forgot, pls update.
