### ISSUE TITLE
 Edited messages are not displayed in ingame

### ISSUE THREAD

**Issue by Daniel-Ric** [BoxOfDevs/CommandShop#15]
### Brief description
 The edited messages in the Config.yml are not accepted

### Steps to reproduce

1. Edit the messages in the config
2. Restart the server once
3. Buy a command and look in the chat.
There stand still the standard news and not from the Cobfig

### Expected result
I would wish that the edited messages from the Config synonymous ingame displayed

### Actual result
 Currently the edited messages are taken from the config not ingame

### Server Information
* CommandShop Version:  https://poggit.pmmp.io/ci/BoxOfDevs/CommandShop/CommandShop?branch=alpha7
* Software Version:  The Last
* Server OS:  Debian 8

### CrashDumps/Errors
``` No errors
Paste your CrashDump or error by replacing this text (DON'T delete the backticks!)
``` No CD

**Comment by HimbeersaftLP** [comment]
What branch are you using?
You should be using master: https://poggit.pmmp.io/ci/BoxOfDevs/CommandShop/CommandShop?branch=master
According to your issue you are still on alpha7, which is very outdated, but I forgot to remove that from the README.

Also make sure to turn off your server, then edit the config, then turn the server on again.

**Comment by Daniel-Ric** [comment]
@HimbeersaftLP ohhh!
Blame on myself....
Thx
