### ISSUE TITLE
Item counter is severely broken and no one ever noticed

### ISSUE THREAD

**Issue by HimbeersaftLP** [BoxOfDevs/CommandShop#17]
### Brief description

Unfairly, too many items get removed.

### Steps to reproduce

1. Try removing one item when you have multiple stacks of only one item (e.g. swords)
2. All of them get removed

### Expected result

Only one gets removed

### Actual result

All of them get removed

The reason for this problem is [this function](https://github.com/BoxOfDevs/CommandShop/blob/a8af891f6dd0d6929e037e2f99f6d7566e7dfa6a/src/BoxOfDevs/CommandShop/CommandShop.php#L129-L155) by Ad5001 that's supposed to remove the correct amount of items, but apparently no one ever tested it with non-stacking items lol.

Possible fix (not yet tested):
```php
private function removeItems(Item $item, BaseInventory $inventory){
     $checkDamage = !$item->hasAnyDamageValue();
     $checkTags = $item->hasCompoundTag();
     $checkCount = $item->getCount() === null ? false : true;
     $count = $item->getCount();
     foreach($inventory->getContents() as $index => $i){
          if($item->equals($i, $checkDamage, $checkTags)){
               if($checkCount && $i->getCount() > $count) {
                    $i->setCount($i->getCount() - $count);
                    $inventory->setItem($index, $i);
                    return;
               } elseif($checkCount && $i->getCount() < $count) {
                    $count -= $i->getCount();
                    $inventory->clear($index);
               } else {
                    $inventory->clear($index);
                    return;
               }
          }
     }
}
```

Thanks to @MCPEATECH for finding this out.

**Comment by aircwo** [comment]
Fix Works 👍

**Comment by HimbeersaftLP** [comment]
@MCPEATECH Yay, thanks for testing

**Comment by aircwo** [comment]
Sorry for the late reply, I use this code on servers and it works fine.
