### ISSUE TITLE
Config.yml TESSERACT

### ISSUE THREAD

**Issue by samp-pinch** [BoxOfDevs/CommandShop#2]
Warning: file_put_contents(C:\PocketMine-MP\plugins\CommandShop/config.yml): failed to open stream: No such file or directory in C:\PocketMine-MP\src\pocketmine\utils\Config.php on line 190
Plugins i use:[Tesseract] [21:50:51] INFO> Plugins (34): FolderPluginLoader v1.0.1, DevTools v1.11.1, superBAR v1.6.2, AdvancedKits v5.1, AntiFly v1.0.0, AntiSpamPro v1.0.8, BetterVIPSlots v2, Broadcaster v1.16, CombatLogger v1.2.0, CommandShop v1.0.0, CosmeticMenu v1.0.0, CustomAlerts v1.6, EconomyAPI v2.0.9, EconomyAuction v2.0.2, EconomyCasino v2.0.2, EconomyJob v2.0.4, EconomyLand v2.0.9, EconomyProperty v2.0.6, EconomyPShop v2.0.2, EconomySell v2.0.7, EconomyShop v2.0.7, EconomyTax v2.0.3, EconomyUsury v1.0.1, EnderAuth v0.0.1, EssentialsPE v2.0.0, FactionsPro v1.3.7.AWZ, iProtector v3.1b, MSpawns v1.5, Neon v1.0.5, NoAdvertisingPE v1.0.1, PurePerms v1.4.0-INDEV, WorldProtect v2.2.0, EconomyAirport v2.0.4, PureChat v1.4.0

**Comment by HimbeersaftLP** [comment]
This is nowhere near finished...

**Comment by Leejit** [comment]
I hope that plugin list isn't on an actual server that anything thinks is any good... 

lol.

**Comment by HimbeersaftLP** [comment]
Wut?

**Comment by eqMFqfFd** [comment]
File should exist before using *file_put_contents()*.
> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by HimbeersaftLP** [comment]
I don't know what kind of mess Tessercrap did with their config system, if you think this is an issue of this plugin, fell free to create one, but don't forget to fill the template properly and say when that happens

**Comment by eqMFqfFd** [comment]
@HimbeersaftLP Probably, but this is something that you have to solve particularly.
> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by HimbeersaftLP** [comment]
I can't solve a problem that I didn't make, complain to the Tessercrap """"devs""""

This plugin is designed to work with PocketMine, I won't fix problems that exist on spoons, fell free to make a Pull Request if you know how to fix it tough

**Comment by AvgZing** [comment]
Tesseract sucks. Use blue light. The plugin works perfectly fine with HTTPS://github.com/BlueLightJapan/BlueLight

**Comment by lavender-sys** [comment]
We do not provide support for spoons or forks. We only support PMMP. If a plugin does not work with a spoon or a fork, your on your own.

**Comment by TheRoyalBlock** [comment]
False, @Dog2puppy. We provide support, but top priority is PMMP

**Comment by AvgZing** [comment]
False, @Dog2puppy. We provide support, but top priority is PMMP. This is the comment that Himbeer deleted. At BoxOfDevs we are supposed to respect other team member's opinions, not delete their comments. I bet you didn't know that it would say that you deleted a comment, did you?

**Comment by AvgZing** [comment]
That simply means, if a commit is possible to make it work with both PMMP and spoons, we will do it. If something causes it to be incompatible with PMMP but compatible with spoons, we will favor PMMP over spoons.

**Comment by HimbeersaftLP** [comment]
1. Says the guy who ***deleted*** (happy?) the whole ToDo comments, and no, I already expected that from you......
2. See the new edit of the readme

**Comment by AvgZing** [comment]
Made that comment appropriate. Also Yeah, I like the new readme

**Comment by Ad5001** [comment]
Hey calm down everybody. It just means that the data folder wasn't creating at plugin load. Simply adding an mkdir($this->getDataFolder()) would solve the whole problem.

**Comment by HimbeersaftLP** [comment]
@Ad5001 PluginBase::saveDefaultConfig uses PluginBase::saveResource which already does mkdir by itself: https://github.com/pmmp/PocketMine-MP/blob/a73c6f1861f70416381db6f91b9b15e1b578ecef/src/pocketmine/plugin/PluginBase.php#L197-L219

Also, this issue doesn't even exist anymore afaik

**Comment by ghost** [comment]
Spoons are trash, why not just use vanilla PocketMine-MP. Plugins are a waste of time, why not just use a Plugin.

**Comment by AvgZing** [comment]
@nathfreder Comment not necessary. Don't bump an old issue.
