### ISSUE TITLE
on your wiki.... 

### ISSUE THREAD

**Issue by Leejit** [BoxOfDevs/CommandShop#6]
LOL, SET RICE... YES, SET ALL THE RICE... SOOO MUCCCHH RIICEEEEE

Go fix that silly typo xD

And thank you guys for making this plugin ! I hope this works smoothly for me <3

**Comment by Leejit** [comment]
![image](https://cloud.githubusercontent.com/assets/17371144/23393893/dfcb74c4-fd53-11e6-8a99-52ec3617366c.png)



so uh... /cshop buycmd example     doesn't work... seriously... wat am I doing wrong ? 
or is this purposely broken to keep it from working for anyone else ?....jw

**Comment by Ad5001** [comment]
Try using /buycmd ;)

**Comment by Leejit** [comment]
oh, okay... 
can you add me as a contributor on here then so I can fix many of your msgs.... or shall I just fork it and make PR's ? ... cuz if thats the case, then your messages could be easier to understand...

**Comment by HimbeersaftLP** [comment]
We are currently working on a translation system, so all the messages will be removed sooner or later anyways

**Comment by Ad5001** [comment]
Starting a fork and then make a PR would be easier for both you and the commit log :)

**Comment by Leejit** [comment]
xD HAH. okay, that worked... jheez, I'mma have to tinker and findout the command tree for this plugin... 

You'd think it would be /cs for all commands, like.. /cs add /cs list /cs setprice /cs buy /cs help, which actually would be helpful if it didn't forward you to a link outside the game xD 

But.. lemme tell you boy, this is one hell of a plugin, a true game changer. 

This plugin is going to change servers. 
You've made history.

This Friday, Saturday, and Sunday, I'll set this up on my server so you can see the creativity you can have with this plugin. 



And I'll fork it, look through code, make some edits, and do a PR and see what you guys think of my minor changes. 

My native language is obviously English, so I can help with those translations...
 👍

**Comment by HimbeersaftLP** [comment]
Thank you!

Closing this issue now, because the rice was tasty, but fixed :P

**Comment by Leejit** [comment]
I love the jokes with you guys.

Yumm rice.
But now its all gone.

xD

<3 thanks again guys.

night tho, it's 1:40am here.xD

**Comment by AvgZing** [comment]
@LordJoshie The rice is not all gone... What's [this?](http://boxofdevs.com/dontask.html)

**Comment by Leejit** [comment]
xD it was from an error on the wiki, it's been fixed... was just jokes :P

**Comment by AvgZing** [comment]
I know ;)

**Comment by HimbeersaftLP** [comment]
> @LordJoshie The rice is not all gone... What's this?

LMAO

**Comment by Leejit** [comment]
x'D  hahaha.
