### ISSUE TITLE
Cant 

### ISSUE THREAD

**Issue by amon28** [BoxOfDevs/CommandShop#7]
### Brief description

Whenever I add 3 new commands in the config when I do /cshop list it doesn't show up it only shows up 2 command the example and the 2nd command but the 3rd doesn't show up

### Steps to reproduce

1. ...
2. ...
3. ...

### Expected result

It will be fix

### Actual result

Gonna be fix
### Server Information
* CommandShop Version: 1.0.0
* Software Version: 
* Server OS: 

### CrashDumps/Errors
```
Paste your CrashDump or error by replacing this text (DON'T delete the backticks!)
```

**Comment by HimbeersaftLP** [comment]
Can you send me your config.yml file? And a screenshot of the output of /cshop list

**Comment by amon28** [comment]
![screenshot_2017-04-15-18-06-05](https://cloud.githubusercontent.com/assets/22851168/25062783/595e1aa4-2206-11e7-9da9-bf49db030cb1.png)

**Comment by HimbeersaftLP** [comment]
I think it's because of the $ before the command name, try deleting ur config and setting up the commands without a $ in the name

**Comment by amon28** [comment]
![screenshot_2017-04-15-18-22-34](https://cloud.githubusercontent.com/assets/22851168/25062893/89cd9da2-2208-11e7-8044-d77eda78c416.png)

**Comment by amon28** [comment]
It still shows 2 commands the example and the 200 but not the middle the 250

**Comment by HimbeersaftLP** [comment]
Normally it shouldn't create multiple "commands:" arrays in the config, habe you tried deleting the config and restarting the server?

**Comment by Ad5001** [comment]
Ok try stoping your server, deleting the config, restarting it, and then re adding the commands without the $.

**Comment by HimbeersaftLP** [comment]
Sorry, but I can't reproduce this, are you sure u are using the newest version?

Screenshot from my config:
![screenshot_20170415-122606](https://cloud.githubusercontent.com/assets/16354747/25062941/1cf2bc02-21d7-11e7-9e59-e45961c7cdd6.png)

**Comment by amon28** [comment]
I'm using the latest version

**Comment by HimbeersaftLP** [comment]
Have you tried what @Ad5001 said?

**Comment by amon28** [comment]
I tried what he said but it didn't work but I copied your Config file it now works Thanks

**Comment by HimbeersaftLP** [comment]
Lol, ok then...
