### ISSUE TITLE
command sign works but it shows empty(no text on sign)

### ISSUE THREAD

**Issue by nasiridrishi** [BoxOfDevs/CommandShop#8]
### Steps to reproduce

1. ...
2. ...
3. ...

### Server Information
* CommandShop Version: 
* Software Version: 
* Server OS: 

### CrashDumps/Errors
```
Paste your CrashDump or error by replacing this text (DON'T delete the backticks!)
```

**Comment by HimbeersaftLP** [comment]
You obviously don't understand how this plugin works, it's you job to write the text on the sign, the plugin only makes it clickable, we do this to allow as much customisation as possible
